// LAS PROMESAS HACEN QUE NUESTRO CODIGO PASE DE SER SINCRONO A ASINCRONO, LO QUE SIGNIFICA QUE PODEMOS EJECUTAR CODIGO QUE TOMA TIEMPO (COMO UNA PETICION A UN SERVIDOR) SIN BLOQUEAR EL RESTO DE NUESTRO CODIGO.

// UNA PROMESA ES UN OBJETO QUE REPRESENTA LA TERMINACION O EL FRACASO DE UNA OPERACION ASINCRONA Y SU RESULTADO.